$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: forecast-deployment-33005
endpoint_name: forecast-endpoint-33005
model: azureml:forecast-model-33005:1
instance_type: Standard_DS3_v2
instance_count: 1
